#!/bin/sh

BUILD_DIR=build
EXEC_NAME=untitled

aclocal
automake --add-missing
autoconf
mkdir -p $BUILD_DIR
cd $BUILD_DIR
../configure
make
sudo make install
valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes $EXEC_NAME
cd ..